### ISSUE TITLE
Unity 2018.2.2f1 compatibility

### ISSUE THREAD

**Issue by glueball** [smkplus/Iridescence#1]
Hello,

Forst of all, many thanks for the tutorials and sharing the shaders ;) I've tried to use the package in the latest unity release, 2018.2.f1, and the following error came out:

> Shader error in 'Smkgames/Surface/Iridescence/Bubble': Too many texture interpolators would be used for ForwardBase pass (11 out of max 10) at line 60

**Comment by smkplus** [comment]
Hello
you're welcome :)

I will fix it but this is common problem that you can easily fix it

Just add or change [shader model](https://docs.unity3d.com/Manual/SL-ShaderCompileTargets.html)

````#pragma target 3.5````

anyway I fixed the problem and commit again
you can use it
